WITH minute_aggregated AS (
    SELECT
        toStartOfMinute(toDateTime64(timestamp / 1000, 3)) AS minute_ts,
        max(timestamp) AS latest_ts
    FROM
        binance_futures_book_snapshot_25.binance_futures_book_snapshot_25_2020_12_19_XRPUSDT
    GROUP BY
        minute_ts
),
     time_series AS (
         SELECT
             arrayJoin(range(toUnixTimestamp(min(minute_ts)), toUnixTimestamp(max(minute_ts)) + 60, 60)) * 1000 AS ts -- 生成从最小到最大时间戳的每分钟时间戳
         FROM
             minute_aggregated
     )
SELECT
    ts.ts AS second_ts,
    anyLast(`asks[0].price`) OVER (ORDER BY second_ts ASC) AS `asks[0].price_filled`,
    anyLast(`asks[0].amount`) OVER (ORDER BY second_ts ASC) AS `asks[0].amount_filled`,
    anyLast(`bids[0].price`) OVER (ORDER BY second_ts ASC) AS `bids[0].price_filled`,
    anyLast(`bids[0].amount`) OVER (ORDER BY second_ts ASC) AS `bids[0].amount_filled`,
    anyLast(`asks[1].price`) OVER (ORDER BY second_ts ASC) AS `asks[1].price_filled`,
    anyLast(`asks[1].amount`) OVER (ORDER BY second_ts ASC) AS `asks[1].amount_filled`,
    anyLast(`bids[1].price`) OVER (ORDER BY second_ts ASC) AS `bids[1].price_filled`,
    anyLast(`bids[1].amount`) OVER (ORDER BY second_ts ASC) AS `bids[1].amount_filled`,
    anyLast(`asks[2].price`) OVER (ORDER BY second_ts ASC) AS `asks[2].price_filled`,
    anyLast(`asks[2].amount`) OVER (ORDER BY second_ts ASC) AS `asks[2].amount_filled`,
    anyLast(`bids[2].price`) OVER (ORDER BY second_ts ASC) AS `bids[2].price_filled`,
    anyLast(`bids[2].amount`) OVER (ORDER BY second_ts ASC) AS `bids[2].amount_filled`,
    anyLast(`asks[3].price`) OVER (ORDER BY second_ts ASC) AS `asks[3].price_filled`,
    anyLast(`asks[3].amount`) OVER (ORDER BY second_ts ASC) AS `asks[3].amount_filled`,
    anyLast(`bids[3].price`) OVER (ORDER BY second_ts ASC) AS `bids[3].price_filled`,
    anyLast(`bids[3].amount`) OVER (ORDER BY second_ts ASC) AS `bids[3].amount_filled`,
    anyLast(`asks[4].price`) OVER (ORDER BY second_ts ASC) AS `asks[4].price_filled`,
    anyLast(`asks[4].amount`) OVER (ORDER BY second_ts ASC) AS `asks[4].amount_filled`,
    anyLast(`bids[4].price`) OVER (ORDER BY second_ts ASC) AS `bids[4].price_filled`,
    anyLast(`bids[4].amount`) OVER (ORDER BY second_ts ASC) AS `bids[4].amount`,
    anyLast(`asks[5].price`) OVER (ORDER BY second_ts ASC) AS `asks[5].price_filled`,
    anyLast(`asks[5].amount`) OVER (ORDER BY second_ts ASC) AS `asks[5].amount_filled`,
    anyLast(`bids[5].price`) OVER (ORDER BY second_ts ASC) AS `bids[5].price_filled`,
    anyLast(`bids[5].amount`) OVER (ORDER BY second_ts ASC) AS `bids[5].amount_filled`,
    anyLast(`asks[6].price`) OVER (ORDER BY second_ts ASC) AS `asks[6].price_filled`,
    anyLast(`asks[6].amount`) OVER (ORDER BY second_ts ASC) AS `asks[6].amount_filled`,
    anyLast(`bids[6].price`) OVER (ORDER BY second_ts ASC) AS `bids[6].price_filled`,
    anyLast(`bids[6].amount`) OVER (ORDER BY second_ts ASC) AS `bids[6].amount_filled`,
    anyLast(`asks[7].price`) OVER (ORDER BY second_ts ASC) AS `asks[7].price_filled`,
    anyLast(`asks[7].amount`) OVER (ORDER BY second_ts ASC) AS `asks[7].amount_filled`,
    anyLast(`bids[7].price`) OVER (ORDER BY second_ts ASC) AS `bids[7].price_filled`,
    anyLast(`bids[7].amount`) OVER (ORDER BY second_ts ASC) AS `bids[7].amount_filled`,
    anyLast(`asks[8].price`) OVER (ORDER BY second_ts ASC) AS `asks[8].price_filled`,
    anyLast(`asks[8].amount`) OVER (ORDER BY second_ts ASC) AS `asks[8].amount_filled`,
    anyLast(`bids[8].price`) OVER (ORDER BY second_ts ASC) AS `bids[8].price_filled`,
    anyLast(`bids[8].amount`) OVER (ORDER BY second_ts ASC) AS `bids[8].amount_filled`,
    anyLast(`asks[9].price`) OVER (ORDER BY second_ts ASC) AS `asks[9].price_filled`,
    anyLast(`asks[9].amount`) OVER (ORDER BY second_ts ASC) AS `asks[9].amount_filled`,
    anyLast(`bids[9].price`) OVER (ORDER BY second_ts ASC) AS `bids[9].price_filled`,
    anyLast(`bids[9].amount`) OVER (ORDER BY second_ts ASC) AS `bids[9].amount_filled`,
    anyLast(`asks[10].price`) OVER (ORDER BY second_ts ASC) AS `asks[10].price_filled`,
    anyLast(`asks[10].amount`) OVER (ORDER BY second_ts ASC) AS `asks[10].amount_filled`,
    anyLast(`bids[10].price`) OVER (ORDER BY second_ts ASC) AS `bids[10].price_filled`,
    anyLast(`bids[10].amount`) OVER (ORDER BY second_ts ASC) AS `bids[10].amount_filled`,
    anyLast(`asks[11].price`) OVER (ORDER BY second_ts ASC) AS `asks[11].price_filled`,
    anyLast(`asks[11].amount`) OVER (ORDER BY second_ts ASC) AS `asks[11].amount_filled`,
    anyLast(`bids[11].price`) OVER (ORDER BY second_ts ASC) AS `bids[11].price_filled`,
    anyLast(`bids[11].amount`) OVER (ORDER BY second_ts ASC) AS `bids[11].amount_filled`,
    anyLast(`asks[12].price`) OVER (ORDER BY second_ts ASC) AS `asks[12].price_filled`,
    anyLast(`asks[12].amount`) OVER (ORDER BY second_ts ASC) AS `asks[12].amount_filled`,
    anyLast(`bids[12].price`) OVER (ORDER BY second_ts ASC) AS `bids[12].price_filled`,
    anyLast(`bids[12].amount`) OVER (ORDER BY second_ts ASC) AS `bids[12].amount_filled`,
    anyLast(`asks[13].price`) OVER (ORDER BY second_ts ASC) AS `asks[13].price_filled`,
    anyLast(`asks[13].amount`) OVER (ORDER BY second_ts ASC) AS `asks[13].amount_filled`,
    anyLast(`bids[13].price`) OVER (ORDER BY second_ts ASC) AS `bids[13].price_filled`,
    anyLast(`bids[13].amount`) OVER (ORDER BY second_ts ASC) AS `bids[13].amount_filled`,
    anyLast(`asks[14].price`) OVER (ORDER BY second_ts ASC) AS `asks[14].price_filled`,
    anyLast(`asks[14].amount`) OVER (ORDER BY second_ts ASC) AS `asks[14].amount_filled`,
    anyLast(`bids[14].price`) OVER (ORDER BY second_ts ASC) AS `bids[14].price_filled`,
    anyLast(`bids[14].amount`) OVER (ORDER BY second_ts ASC) AS `bids[14].amount_filled`,
    anyLast(`asks[15].price`) OVER (ORDER BY second_ts ASC) AS `asks[15].price_filled`,
    anyLast(`asks[15].amount`) OVER (ORDER BY second_ts ASC) AS `asks[15].amount_filled`,
    anyLast(`bids[15].price`) OVER (ORDER BY second_ts ASC) AS `bids[15].price_filled`,
    anyLast(`bids[15].amount`) OVER (ORDER BY second_ts ASC) AS `bids[15].amount_filled`,
    anyLast(`asks[16].price`) OVER (ORDER BY second_ts ASC) AS `asks[16].price_filled`,
    anyLast(`asks[16].amount`) OVER (ORDER BY second_ts ASC) AS `asks[16].amount_filled`,
    anyLast(`bids[16].price`) OVER (ORDER BY second_ts ASC) AS `bids[16].price_filled`,
    anyLast(`bids[16].amount`) OVER (ORDER BY second_ts ASC) AS `bids[16].amount_filled`,
    anyLast(`asks[17].price`) OVER (ORDER BY second_ts ASC) AS `asks[17].price_filled`,
    anyLast(`asks[17].amount`) OVER (ORDER BY second_ts ASC) AS `asks[17].amount_filled`,
    anyLast(`bids[17].price`) OVER (ORDER BY second_ts ASC) AS `bids[17].price_filled`,
    anyLast(`bids[17].amount`) OVER (ORDER BY second_ts ASC) AS `bids[17].amount_filled`,
    anyLast(`asks[18].price`) OVER (ORDER BY second_ts ASC) AS `asks[18].price_filled`,
    anyLast(`asks[18].amount`) OVER (ORDER BY second_ts ASC) AS `asks[18].amount_filled`,
    anyLast(`bids[18].price`) OVER (ORDER BY second_ts ASC) AS `bids[18].price_filled`,
    anyLast(`bids[18].amount`) OVER (ORDER BY second_ts ASC) AS `bids[18].amount_filled`,
    anyLast(`asks[19].price`) OVER (ORDER BY second_ts ASC) AS `asks[19].price_filled`,
    anyLast(`asks[19].amount`) OVER (ORDER BY second_ts ASC) AS `asks[19].amount_filled`,
    anyLast(`bids[19].price`) OVER (ORDER BY second_ts ASC) AS `bids[19].price_filled`,
    anyLast(`bids[19].amount`) OVER (ORDER BY second_ts ASC) AS `bids[19].amount_filled`,
    anyLast(`asks[20].price`) OVER (ORDER BY second_ts ASC) AS `asks[20].price_filled`,
    anyLast(`asks[20].amount`) OVER (ORDER BY second_ts ASC) AS `asks[20].amount_filled`,
    anyLast(`bids[20].price`) OVER (ORDER BY second_ts ASC) AS `bids[20].price_filled`,
    anyLast(`bids[20].amount`) OVER (ORDER BY second_ts ASC) AS `bids[20].amount_filled`,
    anyLast(`asks[21].price`) OVER (ORDER BY second_ts ASC) AS `asks[21].price_filled`,
    anyLast(`asks[21].amount`) OVER (ORDER BY second_ts ASC) AS `asks[21].amount_filled`,
    anyLast(`bids[21].price`) OVER (ORDER BY second_ts ASC) AS `bids[21].price_filled`,
    anyLast(`bids[21].amount`) OVER (ORDER BY second_ts ASC) AS `bids[21].amount_filled`,
    anyLast(`asks[22].price`) OVER (ORDER BY second_ts ASC) AS `asks[22].price_filled`,
    anyLast(`asks[22].amount`) OVER (ORDER BY second_ts ASC) AS `asks[22].amount_filled`,
    anyLast(`bids[22].price`) OVER (ORDER BY second_ts ASC) AS `bids[22].price_filled`,
    anyLast(`bids[22].amount`) OVER (ORDER BY second_ts ASC) AS `bids[22].amount_filled`,
    anyLast(`asks[23].price`) OVER (ORDER BY second_ts ASC) AS `asks[23].price_filled`,
    anyLast(`asks[23].amount`) OVER (ORDER BY second_ts ASC) AS `asks[23].amount_filled`,
    anyLast(`bids[23].price`) OVER (ORDER BY second_ts ASC) AS `bids[23].price_filled`,
    anyLast(`bids[23].amount`) OVER (ORDER BY second_ts ASC) AS `bids[23].amount_filled`,
    anyLast(`asks[24].price`) OVER (ORDER BY second_ts ASC) AS `asks[24].price_filled`,
    anyLast(`asks[24].amount`) OVER (ORDER BY second_ts ASC) AS `asks[24].amount_filled`,
    anyLast(`bids[24].price`) OVER (ORDER BY second_ts ASC) AS `bids[24].price_filled`,
    anyLast(`bids[24].amount`) OVER (ORDER BY second_ts ASC) AS `bids[24].amount_filled`

FROM
    time_series ts
        LEFT JOIN minute_aggregated m ON toUnixTimestamp(minute_ts) * 1000 = ts.ts
        LEFT JOIN binance_futures_book_snapshot_25.binance_futures_book_snapshot_25_2020_12_19_XRPUSDT b ON m.latest_ts = b.timestamp
ORDER BY
    minute_ts ASC;
