CREATE TABLE binance_futures_book_snapshot_25_aggregated
(
    second_ts DateTime64(3),
    timestamp UInt64,
    `asks[0].price` Float64,
    `asks[0].amount` Float64,
    `bids[0].price` Float64,
    `bids[0].amount` Float64,
    `asks[1].price` Float64,
    `asks[1].amount` Float64,
    `bids[1].price` Float64,
    `bids[1].amount` Float64,
    `asks[2].price` Float64,
    `asks[2].amount` Float64,
    `bids[2].price` Float64,
    `bids[2].amount` Float64,
    `asks[3].price` Float64,
    `asks[3].amount` Float64,
    `bids[3].price` Float64,
    `bids[3].amount` Float64,
    `asks[4].price` Float64,
    `asks[4].amount` Float64,
    `bids[4].price` Float64,
    `bids[4].amount` Float64,
    `asks[5].price` Float64,
    `asks[5].amount` Float64,
    `bids[5].price` Float64,
    `bids[5].amount` Float64,
    `asks[6].price` Float64,
    `asks[6].amount` Float64,
    `bids[6].price` Float64,
    `bids[6].amount` Float64,
    `asks[7].price` Float64,
    `asks[7].amount` Float64,
    `bids[7].price` Float64,
    `bids[7].amount` Float64,
    `asks[8].price` Float64,
    `asks[8].amount` Float64,
    `bids[8].price` Float64,
    `bids[8].amount` Float64,
    `asks[9].price` Float64,
    `asks[9].amount` Float64,
    `bids[9].price` Float64,
    `bids[9].amount` Float64,
    `asks[10].price` Float64,
    `asks[10].amount` Float64,
    `bids[10].price` Float64,
    `bids[10].amount` Float64,
    `asks[11].price` Float64,
    `asks[11].amount` Float64,
    `bids[11].price` Float64,
    `bids[11].amount` Float64,
    `asks[12].price` Float64,
    `asks[12].amount` Float64,
    `bids[12].price` Float64,
    `bids[12].amount` Float64,
    `asks[13].price` Float64,
    `asks[13].amount` Float64,
    `bids[13].price` Float64,
    `bids[13].amount` Float64,
    `asks[14].price` Float64,
    `asks[14].amount` Float64,
    `bids[14].price` Float64,
    `bids[14].amount` Float64,
    `asks[15].price` Float64,
    `asks[15].amount` Float64,
    `bids[15].price` Float64,
    `bids[15].amount` Float64,
    `asks[16].price` Float64,
    `asks[16].amount` Float64,
    `bids[16].price` Float64,
    `bids[16].amount` Float64,
    `asks[17].price` Float64,
    `asks[17].amount` Float64,
    `bids[17].price` Float64,
    `bids[17].amount` Float64,
    `asks[18].price` Float64,
    `asks[18].amount` Float64,
    `bids[18].price` Float64,
    `bids[18].amount` Float64,
    `asks[19].price` Float64,
    `asks[19].amount` Float64,
    `bids[19].price` Float64,
    `bids[19].amount` Float64,
    `asks[20].price` Float64,
    `asks[20].amount` Float64,
    `bids[20].price` Float64,
    `bids[20].amount` Float64,
    `asks[21].price` Float64,
    `asks[21].amount` Float64,
    `bids[21].price` Float64,
    `bids[21].amount` Float64,
    `asks[22].price` Float64,
    `asks[22].amount` Float64,
    `bids[22].price` Float64,
    `bids[22].amount` Float64,
    `asks[23].price` Float64,
    `asks[23].amount` Float64,
    `bids[23].price` Float64,
    `bids[23].amount` Float64,
    `asks[24].price` Float64,
    `asks[24].amount` Float64,
    `bids[24].price` Float64,
    `bids[24].amount` Float64
)
    ENGINE = ReplacingMergeTree()
        ORDER BY second_ts;
INSERT INTO binance_futures_book_snapshot_25_aggregated
SELECT
    subquery.second_ts,
    subquery.timestamp,
    subquery.`asks[0].price`,
    subquery.`asks[0].amount`,
    subquery.`bids[0].price`,
    subquery.`bids[0].amount`,
    subquery.`asks[1].price`,
    subquery.`asks[1].amount`,
    subquery.`bids[1].price`,
    subquery.`bids[1].amount`,
    subquery.`asks[2].price`,
    subquery.`asks[2].amount`,
    subquery.`bids[2].price`,
    subquery.`bids[2].amount`,
    subquery.`asks[3].price`,
    subquery.`asks[3].amount`,
    subquery.`bids[3].price`,
    subquery.`bids[3].amount`,
    subquery.`asks[4].price`,
    subquery.`asks[4].amount`,
    subquery.`bids[4].price`,
    subquery.`bids[4].amount`,
    subquery.`asks[5].price`,
    subquery.`asks[5].amount`,
    subquery.`bids[5].price`,
    subquery.`bids[5].amount`,
    subquery.`asks[6].price`,
    subquery.`asks[6].amount`,
    subquery.`bids[6].price`,
    subquery.`bids[6].amount`,
    subquery.`asks[7].price`,
    subquery.`asks[7].amount`,
    subquery.`bids[7].price`,
    subquery.`bids[7].amount`,
    subquery.`asks[8].price`,
    subquery.`asks[8].amount`,
    subquery.`bids[8].price`,
    subquery.`bids[8].amount`,
    subquery.`asks[9].price`,
    subquery.`asks[9].amount`,
    subquery.`bids[9].price`,
    subquery.`bids[9].amount`,
    subquery.`asks[10].price`,
    subquery.`asks[10].amount`,
    subquery.`bids[10].price`,
    subquery.`bids[10].amount`,
    subquery.`asks[11].price`,
    subquery.`asks[11].amount`,
    subquery.`bids[11].price`,
    subquery.`bids[11].amount`,
    subquery.`asks[12].price`,
    subquery.`asks[12].amount`,
    subquery.`bids[12].price`,
    subquery.`bids[12].amount`,
    subquery.`asks[13].price`,
    subquery.`asks[13].amount`,
    subquery.`bids[13].price`,
    subquery.`bids[13].amount`,
    subquery.`asks[14].price`,
    subquery.`asks[14].amount`,
    subquery.`bids[14].price`,
    subquery.`bids[14].amount`,
    subquery.`asks[15].price`,
    subquery.`asks[15].amount`,
    subquery.`bids[15].price`,
    subquery.`bids[15].amount`,
    subquery.`asks[16].price`,
    subquery.`asks[16].amount`,
    subquery.`bids[16].price`,
    subquery.`bids[16].amount`,
    subquery.`asks[17].price`,
    subquery.`asks[17].amount`,
    subquery.`bids[17].price`,
    subquery.`bids[17].amount`,
    subquery.`asks[18].price`,
    subquery.`asks[18].amount`,
    subquery.`bids[18].price`,
    subquery.`bids[18].amount`,
    subquery.`asks[19].price`,
    subquery.`asks[19].amount`,
    subquery.`bids[19].price`,
    subquery.`bids[19].amount`,
    subquery.`asks[20].price`,
    subquery.`asks[20].amount`,
    subquery.`bids[20].price`,
    subquery.`bids[20].amount`,
    subquery.`asks[21].price`,
    subquery.`asks[21].amount`,
    subquery.`bids[21].price`,
    subquery.`bids[21].amount`,
    subquery.`asks[22].price`,
    subquery.`asks[22].amount`,
    subquery.`bids[22].price`,
    subquery.`bids[22].amount`,
    subquery.`asks[23].price`,
    subquery.`asks[23].amount`,
    subquery.`bids[23].price`,
    subquery.`bids[23].amount`,
    subquery.`asks[24].price`,
    subquery.`asks[24].amount`,
    subquery.`bids[24].price`,
    subquery.`bids[24].amount`
FROM
    (
    SELECT
    timestamp,
    toStartOfSecond(toDateTime64(timestamp / 1000000, 3)) AS second_ts,
    `asks[0].price`,
    `asks[0].amount`,
    `bids[0].price`,
    `bids[0].amount`,
    `asks[1].price`,
    `asks[1].amount`,
    `bids[1].price`,
    `bids[1].amount`,
    `asks[2].price`,
    `asks[2].amount`,
    `bids[2].price`,
    `bids[2].amount`,
    `asks[3].price`,
    `asks[3].amount`,
    `bids[3].price`,
    `bids[3].amount`,
    `asks[4].price`,
    `asks[4].amount`,
    `bids[4].price`,
    `bids[4].amount`,
    `asks[5].price`,
    `asks[5].amount`,
    `bids[5].price`,
    `bids[5].amount`,
    `asks[6].price`,
    `asks[6].amount`,
    `bids[6].price`,
    `bids[6].amount`,
    `asks[7].price`,
    `asks[7].amount`,
    `bids[7].price`,
    `bids[7].amount`,
    `asks[8].price`,
    `asks[8].amount`,
    `bids[8].price`,
    `bids[8].amount`,
    `asks[9].price`,
    `asks[9].amount`,
    `bids[9].price`,
    `bids[9].amount`,
    `asks[10].price`,
    `asks[10].amount`,
    `bids[10].price`,
    `bids[10].amount`,
    `asks[11].price`,
    `asks[11].amount`,
    `bids[11].price`,
    `bids[11].amount`,
    `asks[12].price`,
    `asks[12].amount`,
    `bids[12].price`,
    `bids[12].amount`,
    `asks[13].price`,
    `asks[13].amount`,
    `bids[13].price`,
    `bids[13].amount`,
    `asks[14].price`,
    `asks[14].amount`,
    `bids[14].price`,
    `bids[14].amount`,
    `asks[15].price`,
    `asks[15].amount`,
    `bids[15].price`,
    `bids[15].amount`,
    `asks[16].price`,
    `asks[16].amount`,
    `bids[16].price`,
    `bids[16].amount`,
    `asks[17].price`,
    `asks[17].amount`,
    `bids[17].price`,
    `bids[17].amount`,
    `asks[18].price`,
    `asks[18].amount`,
    `bids[18].price`,
    `bids[18].amount`,
    `asks[19].price`,
    `asks[19].amount`,
    `bids[19].price`,
    `bids[19].amount`,
    `asks[20].price`,
    `asks[20].amount`,
    `bids[20].price`,
    `bids[20].amount`,
    `asks[21].price`,
    `asks[21].amount`,
    `bids[21].price`,
    `bids[21].amount`,
    `asks[22].price`,
    `asks[22].amount`,
    `bids[22].price`,
    `bids[22].amount`,
    `asks[23].price`,
    `asks[23].amount`,
    `bids[23].price`,
    `bids[23].amount`,
    `asks[24].price`,
    `asks[24].amount`,
    `bids[24].price`,
    `bids[24].amount`,
    row_number() OVER (PARTITION BY toStartOfSecond(toDateTime64(timestamp / 1000000, 3)) ORDER BY timestamp DESC) AS rn
    FROM
    binance_futures_book_snapshot_25_secs.binance_futures_book_snapshot_25_2020_12_19_XRPUSDT_secs
    ) AS subquery
WHERE subquery.rn = 1
ORDER BY subquery.second_ts ASC;
